### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "test"
}

### Signin an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "test"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Signout the user
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/10

### Find all users with a given email
GET http://localhost:3000/auth?email=pqrs@pqrs.com

### Update a user with a given ID
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "aaaaa@aaaaa.com"
}

### Delete a user with a given ID
DELETE http://localhost:3000/auth/9

# ### Set a color
# GET http://localhost:3000/auth/colors/green

# ### Get a color
# GET http://localhost:3000/auth/colors