### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "pqrs@pqrs.com",
    "password": "pqrspqrs"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=pqrs@pqrs.com

### Update a user with a given ID
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "aaaaa@aaaaa.com"
}

### Delete a user with a given ID
DELETE http://localhost:3000/auth/1